version: '3'

services:
  backend:
    env_file:
        "./server/server.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "pac1687/whois-app-backend"
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "pac1687/whois-app-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"